### ISSUE TITLE
Use JSON for the plugins file, and rename it plugins.json

### ISSUE THREAD

**Issue by tomdxw** [dxw/whippet#28]
Pretty much every dependency manager uses JSON. And the fact that the file is called "plugins" rather than "plugins.ini" makes it hard to recognise that the file is meant to be a configuration file.

If the theory is that JSON is harder to write then we should just add commands to add/remove plugins (composer uses `composer require x`, npm uses `npm install --save x`).

**Comment by Stretch96** [comment]
:+1: I think we should implement this so that there is legacy support for the current format (By means of checking the format, and parsing as necessary) ... That way our current deployments wont go haywire Lol ... Once we've transitioned everything to JSON, it should be safe to remove the legacy support :grimacing:

**Comment by tomdxw** [comment]
@harry-m I looked and actually the README already has an explanation of the format of the `plugins` file. So I'll make sure to read it in future when fiddling with the `plugins` file. :)

After discussing with Harry, we decided to leave this for the moment. Maybe we'll reopen if we discover something we can't do with the current `plugins` file format.
