### ISSUE TITLE
Theme management in Whippet

### ISSUE THREAD

**Issue by harry-m** [dxw/whippet#41]
In order to remove submodules from site repos, we need to be able to manage themes using a "themes" file - in exactly the same way as plugins are currently managed.

There is a set of repos in GovPress github at wordpress-themes/2012,2013,2014 etc. The root repo URL for the themes file should be git@git.dxw.net:wordpress-themes/ (double check this).

As for plugins, existing themes in directories should be untouched. Whippet should only look at themes listed in the themes file.

When this is working, we'll start migrating sites over to this feature.

**Comment by tomdxw** [comment]
Here's my thinking:

- [ ] Add a new module called `dependencies` or `deps`
- [ ] `whippet deps install` reads from `whippet.lock` and installs the themes in the appropriate places
- [ ] `whippet deps update` reads from `whippet.json`, updates `whippet.lock` appropriately, and installs the themes

Maybe at a later date we can add plugins to the new dependency management files.

The reason we should write a new module from scratch instead of basing the work on the existing plugins module is because yesterday I tried to write tests for the plugin module and it's rather difficult. So we'd need to do a lot of work before we can start adding new features via TDD.

**Comment by tomdxw** [comment]
Note about the format of whippet.json:

```
{
  "src": {
    "plugins": "git@git.dxw.net:wordpress-plugins/",
    "themes": "git@git.dxw.net:wordpress-themes/"
  },
    "plugins": [
      {"name": "foo"},                                                                                                                                                                                                                 
      {"name": "bar"},
      {"name": "bat", "version": "v1.5"},
      {"name": "baz", "src": "git@github.com:dxw/baz"},
      {"name": "bert", "version": "v1.5", "src": "git@github.com:dxw/bert"}
    ],
    "themes": [
    ]
}
```

Composer stores a hash in composer.lock. Why do they do that? Should we do that too?

**Comment by harry-m** [comment]
I'd still rather not move to json. It creates a migration headache.

Why not a themes file and themes.lock?

**Comment by tomdxw** [comment]
> EDIT - missed your comment about TDD.

Yeah, I'd like to use the code that's already there, but if I don't write tests there's just going to be a headache later on when we try and change it and we have no tests.

> But I think if we're going to have this we should include plugins in it now.

Makes sense. I'll add it to the TODO list.

> We'll also need a command to convert existing repos to whippet.json.

Yep. That should be fairly straightforward. In fact, we can have it so that if you run `whippet deps install` or `whippet deps update`, it will automatically convert `plugins`/`plugins.lock` to `whippet.json`/`whippet.lock` and just give the user a message telling them to delete the old files and add the new ones to git.

**Comment by harry-m** [comment]
Sounds good.

**Comment by tomdxw** [comment]
The TODO list was getting unmanageably large to be contained in a comment, so I created a PR: #46
