### ISSUE TITLE
"whippet deploy" breaks when there's no wp-content/plugins directory

### ISSUE THREAD

**Issue by tomdxw** [dxw/whippet#7]
In applications without plugins it is necessary to "mkdir wp-content/plugins && touch wp-content/plugins/.gitignore && git add wp-content/plugins/.gitignore" before pushing to a CI-enabled server.

**Comment by harry-m** [comment]
Is this an issue? An app that is created using whippet generate would not be missing any of those files.

What is ```wp-content/plugins/.gitignore``` for? Whippet will only manage ```/.gitignore```, I think all ignores should happen there?

**Comment by tomdxw** [comment]
This was an issue on the govsite repository. I see that "generate app" leaves a wp-content/plugins/index.php file. Not sure why somebody forgot to check that in.

> What is wp-content/plugins/.gitignore for?

To make git create the wp-content/plugins directory.

I'll close this since the generator creates a file in that directory.

**Comment by dgmstuart** [comment]
> An app that is created using whippet generate would not be missing any of those files.

@harry-m I'm not sure that's an argument? Stuff _will_ get messed up,,,

I think in order to avoid bugs and pain the app should either: 
not blow up if those files aren't really required, 
OR create them 
OR fail as soon as they are known to be missing. 

Check out the work I did (ages ago) in `lib/modules/plugin.class.php` along those lines

**Comment by harry-m** [comment]
Happy to add those checks somewhere sensible.
